name: Update Jira Issue After PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  update-jira:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Extract Jira Issue Key from PR title
        id: extract
        run: |
          echo "PR Title: ${{ github.event.pull_request.title }}"
          if [[ "${{ github.event.pull_request.title }}" =~ (TODO-[0-9]+) ]]; then
            echo "issue_key=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "No issue key found"
            exit 1
          fi

      - name: Move issue to Done on Jira
        run: |
          curl -X POST \
            -u "${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
            --url "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.extract.outputs.issue_key }}/transitions" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -d '{
              "transition": {
                "id": "31"
              }
            }'
